### ISSUE TITLE
Resolutions higher than that of the cat image cause tiling

### ISSUE THREAD

**Issue by matosauce** [t-duex/internet-for-the-day#5]
![image](https://user-images.githubusercontent.com/9835503/38708900-faf9c48c-3e7d-11e8-87c9-c5c9b3fd36b3.png)

**Comment by shankera** [comment]
How does this fix affect portrait oriented monitors?

**Comment by shankera** [comment]
https://github.com/t-duex/internet-for-the-day/pull/6

This fix, i mean
